<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Eliminar preguntas existentes
        Question::query()->delete();

        $questions = [
            // PROGRAMACIÓN - 10 preguntas tipo test
            [
                'subject' => 'programación',
                'question_text' => '¿Qué es una variable en programación?',
                'option_a' => 'Un espacio de memoria para almacenar datos',
                'option_b' => 'Un tipo de dato específico',
                'option_c' => 'Una función predefinida',
                'option_d' => 'Un bucle infinito',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Cuál es la diferencia entre let y const en JavaScript?',
                'option_a' => 'let permite reasignación, const no',
                'option_b' => 'const permite reasignación, let no',
                'option_c' => 'No hay diferencia',
                'option_d' => 'let es para números, const para texto',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Qué es un API REST?',
                'option_a' => 'Una interfaz para comunicación entre sistemas',
                'option_b' => 'Una base de datos',
                'option_c' => 'Un lenguaje de programación',
                'option_d' => 'Un framework frontend',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Cuál es el propósito de un bucle for?',
                'option_a' => 'Repetir código múltiples veces',
                'option_b' => 'Definir una función',
                'option_c' => 'Crear una variable',
                'option_d' => 'Manejar errores',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Qué significa "DRY" en programación?',
                'option_a' => 'Don\'t Repeat Yourself',
                'option_b' => 'Do Right Yourself',
                'option_c' => 'Data Ready Yesterday',
                'option_d' => 'Debug Regular Yearly',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Cuál es la función principal de Git?',
                'option_a' => 'Control de versiones',
                'option_b' => 'Compilar código',
                'option_c' => 'Diseñar interfaces',
                'option_d' => 'Optimizar rendimiento',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Qué es una función en programación?',
                'option_a' => 'Un bloque de código reutilizable',
                'option_b' => 'Una variable global',
                'option_c' => 'Un tipo de dato',
                'option_d' => 'Un bucle infinito',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Cuál es la diferencia entre frontend y backend?',
                'option_a' => 'Frontend es interfaz, backend es lógica del servidor',
                'option_b' => 'Frontend es base de datos, backend es diseño',
                'option_c' => 'No hay diferencia',
                'option_d' => 'Frontend es para móviles, backend para escritorio',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Qué es un array?',
                'option_a' => 'Una colección ordenada de elementos',
                'option_b' => 'Una función matemática',
                'option_c' => 'Un tipo de bucle',
                'option_d' => 'Una variable constante',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'programación',
                'question_text' => '¿Cuál es tu nivel de experiencia con programación?',
                'option_a' => 'Principiante - Estoy aprendiendo',
                'option_b' => 'Intermedio - Tengo proyectos personales',
                'option_c' => 'Avanzado - Trabajo profesionalmente',
                'option_d' => 'Experto - Enseño a otros',
                'correct_option' => 'b',
            ],

            // DISEÑO - 10 preguntas tipo test
            [
                'subject' => 'diseño',
                'question_text' => '¿Qué es la teoría del color en diseño gráfico?',
                'option_a' => 'Un conjunto de reglas para mezclar colores',
                'option_b' => 'Un software de diseño',
                'option_c' => 'Una técnica de impresión',
                'option_d' => 'Un estilo artístico',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Cuál es el propósito del diseño UX?',
                'option_a' => 'Mejorar la experiencia del usuario',
                'option_b' => 'Crear logos atractivos',
                'option_c' => 'Optimizar impresión',
                'option_d' => 'Desarrollar código',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Qué es una paleta de colores?',
                'option_a' => 'Un conjunto de colores coordinados',
                'option_b' => 'Una herramienta de dibujo',
                'option_c' => 'Un formato de imagen',
                'option_d' => 'Una técnica de tipografía',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Cuál es la diferencia entre RGB y CMYK?',
                'option_a' => 'RGB para pantallas, CMYK para impresión',
                'option_b' => 'CMYK para pantallas, RGB para impresión',
                'option_c' => 'Son lo mismo',
                'option_d' => 'RGB es para fotos, CMYK para videos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Qué es la tipografía en diseño?',
                'option_a' => 'El arte de organizar letras y texto',
                'option_b' => 'La creación de logos',
                'option_c' => 'La edición de fotos',
                'option_d' => 'La animación de gráficos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Cuál es el propósito de una maquetación?',
                'option_a' => 'Organizar elementos visuales en una página',
                'option_b' => 'Crear animaciones',
                'option_c' => 'Editar videos',
                'option_d' => 'Programar aplicaciones',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Qué es el "white space" en diseño?',
                'option_a' => 'Espacio vacío intencional',
                'option_b' => 'Color blanco puro',
                'option_c' => 'Texto en blanco',
                'option_d' => 'Fondo transparente',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Cuál es la función principal de Adobe Illustrator?',
                'option_a' => 'Crear gráficos vectoriales',
                'option_b' => 'Editar fotos',
                'option_c' => 'Diseñar páginas web',
                'option_d' => 'Producir videos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Qué es un mockup en diseño?',
                'option_a' => 'Una representación visual del producto final',
                'option_b' => 'Un boceto inicial',
                'option_c' => 'Un logo finalizado',
                'option_d' => 'Una paleta de colores',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'diseño',
                'question_text' => '¿Cuál es tu experiencia con herramientas de diseño?',
                'option_a' => 'Principiante - Nunca he usado programas de diseño',
                'option_b' => 'Intermedio - Conozco lo básico de Photoshop/Illustrator',
                'option_c' => 'Avanzado - Tengo experiencia con varios programas',
                'option_d' => 'Experto - Soy profesional del diseño',
                'correct_option' => 'b',
            ],

            // IDIOMAS - 10 preguntas tipo test
            [
                'subject' => 'idiomas',
                'question_text' => '¿Cuál es tu nivel actual de inglés?',
                'option_a' => 'Principiante (A1-A2)',
                'option_b' => 'Intermedio (B1-B2)',
                'option_c' => 'Avanzado (C1-C2)',
                'option_d' => 'Nativo',
                'correct_option' => 'b',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Qué habilidad es más importante para aprender un idioma?',
                'option_a' => 'La práctica constante',
                'option_b' => 'La memorización de reglas',
                'option_c' => 'Solo leer libros',
                'option_d' => 'Ver películas sin subtítulos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Cuál es la diferencia entre "affect" y "effect" en inglés?',
                'option_a' => 'Affect es verbo, effect es sustantivo',
                'option_b' => 'Effect es verbo, affect es sustantivo',
                'option_c' => 'Son sinónimos',
                'option_d' => 'No se usan en inglés',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Qué método prefieres para aprender vocabulario?',
                'option_a' => 'Flashcards y repetición',
                'option_b' => 'Leer extensivamente',
                'option_c' => 'Ver series en el idioma',
                'option_d' => 'Hablar con nativos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Cuál es el tiempo verbal más difícil en inglés?',
                'option_a' => 'Present Perfect',
                'option_b' => 'Simple Present',
                'option_c' => 'Simple Past',
                'option_d' => 'Future Simple',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Prefieres clases de gramática o conversación?',
                'option_a' => 'Solo gramática',
                'option_b' => 'Solo conversación',
                'option_c' => 'Mix de ambas',
                'option_d' => 'Depende del profesor',
                'correct_option' => 'c',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Qué significa "phrasal verb" en inglés?',
                'option_a' => 'Verbo compuesto con preposición',
                'option_b' => 'Verbo irregular',
                'option_c' => 'Verbo modal',
                'option_d' => 'Verbo en pasado',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Cuál es tu objetivo principal al aprender este idioma?',
                'option_a' => 'Viajar y comunicarme',
                'option_b' => 'Trabajo profesional',
                'option_c' => 'Estudios académicos',
                'option_d' => 'Interés personal',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Qué es más difícil: pronunciación o gramática?',
                'option_a' => 'Pronunciación',
                'option_b' => 'Gramática',
                'option_c' => 'Ambas son igualmente difíciles',
                'option_d' => 'Ninguna es difícil',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'idiomas',
                'question_text' => '¿Cuánto tiempo dedicas a practicar el idioma semanalmente?',
                'option_a' => 'Menos de 2 horas',
                'option_b' => '2-5 horas',
                'option_c' => '5-10 horas',
                'option_d' => 'Más de 10 horas',
                'correct_option' => 'b',
            ],

            // MÚSICA - 10 preguntas tipo test
            [
                'subject' => 'música',
                'question_text' => '¿Sabes leer partituras musicales?',
                'option_a' => 'No, no sé leer partituras',
                'option_b' => 'Sí, a nivel básico',
                'option_c' => 'Sí, a nivel intermedio',
                'option_d' => 'Sí, soy experto leyendo partituras',
                'correct_option' => 'b',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Cuál es la diferencia entre mayor y menor en música?',
                'option_a' => 'Mayor suena feliz, menor suena triste',
                'option_b' => 'Mayor es más rápido, menor es más lento',
                'option_c' => 'Mayor es para voz, menor para instrumentos',
                'option_d' => 'No hay diferencia',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Qué es un acorde en música?',
                'option_a' => 'Tres o más notas tocadas simultáneamente',
                'option_b' => 'Una sola nota',
                'option_c' => 'Un ritmo específico',
                'option_d' => 'Una letra de canción',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Cuál es el instrumento más fácil de aprender?',
                'option_a' => 'Ukelele',
                'option_b' => 'Violín',
                'option_c' => 'Piano',
                'option_d' => 'Batería',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Qué es el tempo en música?',
                'option_a' => 'La velocidad de la pieza musical',
                'option_b' => 'El volumen de la música',
                'option_c' => 'El tono de la voz',
                'option_d' => 'El estilo musical',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Qué instrumento te gustaría aprender?',
                'option_a' => 'Guitarra',
                'option_b' => 'Piano',
                'option_c' => 'Batería',
                'option_d' => 'Violín',
                'correct_option' => 'b',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Cuál es tu experiencia previa con música?',
                'option_a' => 'Ninguna, soy principiante absoluto',
                'option_b' => 'He tocado algún instrumento básico',
                'option_c' => 'Tengo conocimientos musicales sólidos',
                'option_d' => 'Soy músico profesional',
                'correct_option' => 'b',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Qué es el ritmo en música?',
                'option_a' => 'El patrón de pulsaciones regulares',
                'option_b' => 'La melodía principal',
                'option_c' => 'La armonía de los acordes',
                'option_d' => 'La letra de la canción',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Prefieres música clásica o moderna?',
                'option_a' => 'Clásica',
                'option_b' => 'Moderna',
                'option_c' => 'Ambas por igual',
                'option_d' => 'No tengo preferencia',
                'correct_option' => 'c',
            ],
            [
                'subject' => 'música',
                'question_text' => '¿Cuánto tiempo practicas música semanalmente?',
                'option_a' => 'Menos de 1 hora',
                'option_b' => '1-3 horas',
                'option_c' => '3-5 horas',
                'option_d' => 'Más de 5 horas',
                'correct_option' => 'b',
            ],

            // MARKETING - 10 preguntas tipo test
            [
                'subject' => 'marketing',
                'question_text' => '¿Qué es el SEO en marketing digital?',
                'option_a' => 'Search Engine Optimization',
                'option_b' => 'Social Media Optimization',
                'option_c' => 'Sales Enhancement Operations',
                'option_d' => 'Strategic Email Outreach',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Cuál es el propósito del marketing de contenidos?',
                'option_a' => 'Atraer y retener clientes con información valiosa',
                'option_b' => 'Vender directamente productos',
                'option_c' => 'Reducir costos de publicidad',
                'option_d' => 'Competir con otras empresas',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Qué es un "lead" en marketing?',
                'option_a' => 'Un cliente potencial',
                'option_b' => 'Un cliente fiel',
                'option_c' => 'Un competidor',
                'option_d' => 'Un producto',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Cuál es la diferencia entre B2B y B2C?',
                'option_a' => 'B2B es empresa a empresa, B2C es empresa a consumidor',
                'option_b' => 'B2C es empresa a empresa, B2B es empresa a consumidor',
                'option_c' => 'Son lo mismo',
                'option_d' => 'B2B es online, B2C es offline',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Qué es el "funnel" de marketing?',
                'option_a' => 'El recorrido del cliente desde conocimiento hasta compra',
                'option_b' => 'Un tipo de publicidad',
                'option_c' => 'Una herramienta de análisis',
                'option_d' => 'Un presupuesto de marketing',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Cuál es tu experiencia con redes sociales para negocios?',
                'option_a' => 'Sin experiencia',
                'option_b' => 'Uso personal básico',
                'option_c' => 'He gestionado cuentas de negocios',
                'option_d' => 'Soy experto en marketing digital',
                'correct_option' => 'c',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Qué es el "branding"?',
                'option_a' => 'La construcción de la marca',
                'option_b' => 'La creación de logos',
                'option_c' => 'La publicidad tradicional',
                'option_d' => 'El análisis de datos',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Cuál es la métrica más importante en redes sociales?',
                'option_a' => 'Engagement (interacción)',
                'option_b' => 'Número de seguidores',
                'option_c' => 'Publicaciones diarias',
                'option_d' => 'Likes por publicación',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Qué es el email marketing?',
                'option_a' => 'Marketing directo por correo electrónico',
                'option_b' => 'Publicidad en correos gratuitos',
                'option_c' => 'Marketing para empresas de correo',
                'option_d' => 'Spam masivo',
                'correct_option' => 'a',
            ],
            [
                'subject' => 'marketing',
                'question_text' => '¿Cuál es tu nivel de conocimiento en marketing?',
                'option_a' => 'Principiante - Estoy aprendiendo',
                'option_b' => 'Intermedio - Tengo experiencia práctica',
                'option_c' => 'Avanzado - Trabajo en marketing',
                'option_d' => 'Experto - Soy consultor de marketing',
                'correct_option' => 'b',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
