version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aralin_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aralin_db
      MYSQL_ROOT_PASSWORD: aralin123
      MYSQL_PASSWORD: aralin123
      MYSQL_USER: aralin_user
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aralin_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: aralin_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: aralin123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - aralin_network

volumes:
  mysql_data:

networks:
  aralin_network:
    driver: bridge
